---
nocite: "@*"
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-latex.tex
bibliography: publications.bib
geometry: margin=.7in

title: "Résumé - March 2019"
author: Nathaniel Price
orcid:  "0000-0002-6450-617X"
fontawesome: yes
email: natbprice@gmail.com
twitter: DayduhScientist
github: natbprice
phone: "+1 904 315 2486"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---


# Education

**Ph.D. Mechanical Engineering** (jointly conferred) \hfill 2012 - 16  
*University of Florida, Gainesville, Florida, USA*   
*École Nationale Supérieure des Mines de Saint-Étienne, Saint-Étienne, France*  

**M.S. Mechanical Engineering** \hfill 2012 - 14  
*University of Florida, Gainesville, Florida, USA*

**Graduate Certificate in Scientific Computing** \hfill 2012 - 14  
*University of Florida, Gainesville, Forida, USA*

**B.S. Mechanical Engineering** \hfill 2008 - 12  
*University of Florida, Gainesville, Florida, USA*

# Professional Experience

**Post-doctoral Research Associate**   \hfill September 2016 - present  
*School of Natural Resources*  
*University of Nebraska-Lincoln, Lincoln, Nebraska, USA*

- Data scientist for human dimensions research group
- Mentor graduate students and train students in statistical analysis techniques
- Developed exploratory data analysis dashboard in R for SQL sportsperson customer database 


**Graduate Research Assistant**    \hfill August 2012 - August 2016  
*Department of Mechanical & Aerospace Engineering*  
*University of Florida, Gainesville, Florida, USA*

- Integrated machine learning (e.g., Gaussian process), optimization, and
uncertainty propagation to design engineering systems considering future 
decision making process
-	Collaboratively developed optimization-based method for NASA Uncertainty 
Quantification Challenge


**Ph.D. Student Researcher** \hfill October 2014 - April 2016     
*ONERA – The French Aerospace Lab, Palaiseau, France*  

- Developed and applied a novel method for optimal design of sounding rocket under uncertainty
- Co-authored book chapter on space vehicle design under uncertainty

**Undergraduate Research Assistant** \hfill May 2011 - May 2012  
*Department of Mechanical & Aerospace Engineering*  
*University of Florida, Gainesville, Florida, USA*

-	Developed Python code for parameterized finite element modeling of rigid sternal fixation
-	Analyzed effects of patient variability and plate designs on stability of sternal fixation
-	Presented award winning research at top conferences

**Engineer Intern** \hfill January 2005 - August 2012  
*E&S Consulting Inc., St. Augustine, Florida, USA*

-	Assisted with failure analysis investigations (inspections, materials testing, reports, research)

**Launch Engineer Intern** \hfill August 2010 - December 2010
*SpaceX, Cape Canaveral, Florida, USA*

- Performed maintenance of launch vehicle ground systems
- Assisted in rollout and launch of Falcon 9 and Dragon spacecraft

**Undergraduate Research Assistant** \hfill May 2011 - May 2012  
*Department of Materials Science & Engineering*  
*University of Florida, Gainesville, Florida, USA*  

- Developed Matlab code for compliance correction of compression / tensile strength test data
- Machined magnesium tensile strength test specimens

# Publications
