---
name: Nathaniel Price
position: "Data Scientist"
address: "335 S. 46th St. Lincon, NE 68510"
phone: +1 904 315 2486
email: "natbprice@gmail.com"
twitter: DayduhScientist
github: natbprice
linkedin: natbprice
date: "`r format(Sys.time(), '%B %Y')`"
output: function(...) vitae::cv_document(..., template = "pricetemplate.tex", citation_package = "biblatex")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(vitae)
library(lubridate)
library(glue)
```

```{r loadData}

# Education
education <- read_csv("education.csv",
                      locale = locale(encoding = 'ISO-8859-1'),
                      col_types = cols(
                        begin = col_date("%m/%d/%y"),
                        end = col_date("%m/%d/%y")
                        )
                      )

# Job titles
job.titles <- read_csv("job-titles.csv",
                      locale = locale(encoding = 'ISO-8859-1'),
                      col_types = cols(
                        begin = col_date("%m/%d/%y"),
                        end = col_date("%m/%d/%y")
                        )
)

# Job descriptions
job.descriptions <- read_csv("job-descriptions.csv",
                      locale = locale(encoding = 'ISO-8859-1')
)

```

# Education

```{r education, results = "asis"}
education %>%
  detailed_entries(
    what = degree,
    when = as.character(glue("{year(begin)} - {year(end)}")),
    with = university,
    where = glue("{city}, {region}, {country}")
  )
```

# Experience

```{r experience1}
job.titles %>% 
  left_join(job.descriptions) %>% 
  filter(jobId >= 2) %>% 
  detailed_entries(
    what = position,
    when = as.character(
      glue("{year(begin)} - {if_else(!is.na(end), as.character(year(end)), 'present')}")),
    with = employer,
    where = glue("{city}, {region}, {country}"),
    why = accomplishments)

```

```{r experience2}

job.titles %>% 
  left_join(job.descriptions) %>% 
  filter(jobId < 2) %>% 
  detailed_entries(
    what = position,
    when = as.character(
      glue("{year(begin)} - {if_else(!is.na(end), as.character(year(end)), 'present')}")),
    with = employer,
    where = glue("{city}, {region}, {country}"),
    why = accomplishments)
```


# Publications

```{r pubSetup}
posters <- c("price_design_2012", "price_effects_2012")
software <- c("price_radsets_2019", "price_tvdiff_2019")
```


## Journal Articles and Book Chapters
```{r journalPapers}
bibliography_entries("publications.bib") %>%
  filter(bibtype %in% c("Article", "InCollection")) %>%
  arrange(desc(year), author)
```

## Conference Papers
```{r conferencePapers}
bibliography_entries("publications.bib") %>%
  filter(bibtype %in% c("InProceedings"),
         !key %in% posters) %>%
  arrange(desc(year), author)
```

## Oral Presentations
```{r oralPresentations}
bibliography_entries("publications.bib") %>%
  filter(bibtype == "Misc",
         !key %in% software) %>%
  arrange(desc(year), author)
```

## Conference Posters
```{r posters}
bibliography_entries("publications.bib") %>%
  filter(key %in% posters) %>%
  arrange(desc(year), author)
```

## Software (Github: natbprice)
```{r software}
bibliography_entries("publications.bib") %>%
  filter(key %in% software) %>%
  arrange(desc(year), author)
```
